name: "action-compose-management-deployment"

on:
  workflow_call:
    inputs:
      actions:
        type: "string"

jobs:
  check_changed_files:
    uses: ./.github/workflows/single-task_detect-changes.yml
    secrets: inherit
  
  check_compose_files:
    needs: check_changed_files
    if: |
      (needs.check_changed_files.outputs.changed_files_added != '') ||
      (needs.check_changed_files.outputs.changed_files_modified != '') ||
      (needs.check_changed_files.outputs.changed_files_renamed != '')
    uses: ./.github/workflows/single-task_compose-linter.yml
    secrets: inherit

  handle_gpg:
    needs:
      - check_changed_files
      - check_compose_files
    uses: ./.github/workflows/single-task_gpg-handler.yml
    secrets: inherit

  stop_modified_removed_renamed_container:
    needs: 
      - check_changed_files
      - check_compose_files
      - handle_gpg
    if: |
      (needs.check_changed_files.outputs.changed_files_modified != '') || 
      (needs.check_changed_files.outputs.changed_files_removed != '') || 
      (needs.check_changed_files.outputs.changed_files_renamed != '')
    uses: ./.github/workflows/single-task_stop-containers.yml
    secrets: inherit


  # sync the existing git repo
  git_sync:
    needs: 
      - check_changed_files
      - check_compose_files
      - handle_gpg
      - stop_modified_removed_renamed_container
    if: |
      always() &&
      !cancelled() &&
      !failure() &&
      (
        (needs.check_changed_files.outputs.changed_files_added != '') ||
        (needs.check_changed_files.outputs.changed_files_modified != '') ||
        (needs.check_changed_files.outputs.changed_files_renamed != '')
      ) &&
      (
        (needs.stop_modified_removed_renamed_container.result == 'skipped') || (needs.stop_modified_removed_renamed_container.result == 'success')
      )
    uses: ./.github/workflows/single-task_git-sync.yml
    secrets: inherit
    

  # unlock potential new secret files
  unlock_secret_files:
    needs: 
      - check_changed_files
      - check_compose_files
      - handle_gpg
      - stop_modified_removed_renamed_container
      - git_sync
    if: |
      always() &&
      !cancelled() &&
      !failure() &&
      (
        (needs.check_changed_files.outputs.changed_files_added != '') ||
        (needs.check_changed_files.outputs.changed_files_modified != '') ||
        (needs.check_changed_files.outputs.changed_files_renamed != '')
      ) &&
      (
        (needs.stop_modified_removed_renamed_container.result == 'skipped') || (needs.stop_modified_removed_renamed_container.result == 'success')
      ) &&
      needs.git_sync.result == 'success'
    uses: ./.github/workflows/single-task_unlock-secret-files.yml
    secrets: inherit

  start_added_modified_renamed_container:
    needs: 
      - check_changed_files
      - check_compose_files
      - handle_gpg
      - stop_modified_removed_renamed_container
      - git_sync
      - unlock_secret_files
    if: |
      always() &&
      !cancelled() &&
      !failure() &&
      (
        (needs.check_changed_files.outputs.changed_files_added != '') ||
        (needs.check_changed_files.outputs.changed_files_modified != '') ||
        (needs.check_changed_files.outputs.changed_files_renamed != '')
      ) &&
      (
        (needs.stop_modified_removed_renamed_container.result == 'skipped') || (needs.stop_modified_removed_renamed_container.result == 'success')
      ) &&
      needs.git_sync.result == 'success' &&
      needs.unlock_secret_files.result == 'success'
    uses: ./.github/workflows/single-task_start-containers.yml
    secrets: inherit
