
on:
    workflow_call:
      inputs:
        matrix_hosts:
          required: true
          type: string
        changed_files_modified:
          required: true
          type: string
        changed_files_removed:
          required: true
          type: string
        changed_files_renamed:
          required: true
          type: string

jobs:
  stop_modified_removed_renamed_container:
    runs-on: self-hosted
    strategy:
      matrix:
        host: [ "${{ inputs.matrix_hosts }}" ]
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars[format('REMOTE_HOST_{0}', matrix.host)] }}
          username: ${{ vars[format('REMOTE_USER_{0}', matrix.host)] }}
          key: ${{ secrets[format('REMOTE_USER_SSH_PRIVATE_KEY_{0}', matrix.host)] }}
          timeout: 10s
          command_timeout: 10m
          script: |
            for host in $(echo "${{ matrix.host }}" | tr ' ' '\n' | tr '_' '-' | tr '[:upper:]' '[:lower:]')
            do

              # handle modified containers
              for container in $(echo "${{ inputs.changed_files_modified }}" | tr ' ' '\n')
              do
                if [[ "$container" = *"$host"* ]]; then
                  # change into right folder and start container
                  cd  ${{ vars.REMOTE_DOCKER_REPO_PATH_PARENT }}/${{ vars.REMOTE_DOCKER_REPO_FOLDER_NAME }}/$(echo "$container" | sed 's:[^/]*$::')
                  if [[ -f "docker-compose.secret.yml" ]]; then
                    docker-compose -f docker-compose.yml -f docker-compose.secret.yml down
                  else
                    docker-compose down
                  fi
                fi
              done
            
              for container in $(echo "${{ inputs.changed_files_removed }}" | tr ' ' '\n')
              do
                if [[ "$container" = *"$host"* ]]; then
                  # change into right folder and start container
                  cd  ${{ vars.REMOTE_DOCKER_REPO_PATH_PARENT }}/${{ vars.REMOTE_DOCKER_REPO_FOLDER_NAME }}/$(echo "$container" | sed 's:[^/]*$::')
                  if [[ -f "docker-compose.secret.yml" ]]; then
                    docker-compose -f docker-compose.yml -f docker-compose.secret.yml down
                  else
                    docker-compose down
                  fi
                fi
              done

              # handle renamed containers
              for container in $(echo "${{ inputs.changed_files_renamed }}" | tr ' ' '\n')
              do
                if [[ "$container" = *"$host"* ]]; then
                  # change into right folder and start container
                  cd  ${{ vars.REMOTE_DOCKER_REPO_PATH_PARENT }}/${{ vars.REMOTE_DOCKER_REPO_FOLDER_NAME }}/$(echo "$container" | sed 's:[^/]*$::')
                  if [[ -f "docker-compose.secret.yml" ]]; then
                    docker-compose -f docker-compose.yml -f docker-compose.secret.yml down
                  else
                    docker-compose down
                  fi
                fi
              done
            
            done
