
on:
  workflow_call:


jobs:
  gpg-handler:
    runs-on: self-hosted
    strategy:
      matrix:
        host: [ "${{ needs.check_changed_files.outputs.matrix_hosts }}" ]
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars[format('REMOTE_HOST_{0}', matrix.host)] }}
          username: ${{ vars[format('REMOTE_USER_{0}', matrix.host)] }}
          key: ${{ secrets[format('REMOTE_USER_SSH_PRIVATE_KEY_{0}', matrix.host)] }}
          timeout: 10s
          command_timeout: 1m
          script: |
            # check and install gpg key IF it is missing
            if [[ $(gpg --batch --no-tty -K | grep -i "${{ vars[format('GPG_MAIL_{0}', matrix.host)] }}" | wc -l) == 0 ]]; then
              echo "${{ secrets[format('GPG_PRIVATE_KEY_{0}', matrix.host)] }}" | gpg --no-tty --batch --passphrase ${{ secrets[format('GPG_PASSPHRASE_{0}', matrix.host)] }} --pinentry-mode loopback --import
            else
              echo "Key is already imported. No change needed."
            fi