
on:
  workflow_call:
    inputs:
      changed_files_all_csv:
        required: true
        type: string


jobs:
  compose_linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        list_of_files: [ "${{ inputs.changed_files_all_csv }}" ]
    steps:
      - uses: actions/checkout@v4
      - name: "check compose files"
        uses: sjafferali/docker-compose-lint-action@v0.1.2
        with:
          compose-file: "${{ matrix.list_of_files }}"