on:
  workflow_call:
    inputs:
      matrix_hosts:
        required: true
        type: string
  
jobs:
  unlock_secret_files:
    runs-on: self-hosted
    strategy:
      matrix:
        host: [ "${{ inputs.matrix_hosts }}" ]
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars[format('REMOTE_HOST_{0}', matrix.host)] }}
          username: ${{ vars[format('REMOTE_USER_{0}', matrix.host)] }}
          key: ${{ secrets[format('REMOTE_USER_SSH_PRIVATE_KEY_{0}', matrix.host)] }}
          timeout: 10s
          command_timeout: 1m
          request_pty: true
          script: |
            cd ${{ vars.REMOTE_DOCKER_REPO_PATH_PARENT }}/${{ vars.REMOTE_DOCKER_REPO_FOLDER_NAME }}
            git secret reveal -f -v -P -p ${{ secrets[format('GPG_PASSPHRASE_{0}', matrix.host)] }}